<?php
namespace ideal;

use library\Plugin;

class IdealPlugin extends Plugin
{
    private $html = '';
    private $postErrors = [];

    public $checkName;
    public $address;    

    /**
     * 
     */
    public function __construct()
    {
        $this->name = 'kasoko_ideal';
        $this->category = 'payments_methode';
        $this->version = '1.0.0';
        $this->author = 'Kasoko';
        $this->controllers = array('IdealController', 'IdealValidation');
        $this->currencies = true;
        $this->currencies_mode = 'checkbox';
        $this->checkName = '';
        $this->address = '';
        $this->bootstrap = true;
        parent::__construct();
    }

    /**
     * 
     * @return string
     */
    public function getContent()
    {
        return '<h2>HERE THE CONTENT GENERATED BY MODULE [iDeal Payment]</h2>';
    }

}
