<div class="wrapper">
    <div class="table-responsive">
        <table class="table table-striped table-condensed" id="product_list">
            <caption>Carriers
                <a class="btn btn-default btn-primary action-btn" title="Add a new carrier" href="/admin/shipping/edit_carrier" data-toggle="modal">
                    <span class="glyphicon glyphicon-plus-sign"></span>
                </a>
            </caption>
            <thead>
                <tr>
                    <th class="object-title">
                        <a href="#">ID</a>
                    </th>
                    <th class="object-title">
                        <a href="#">Name</a>
                    </th>
                    <th class="object-title">
                        <a href="#">Logo</a>
                    </th>
                    <th class="object-title">
                        <a href="#">Delay</a>
                    </th>
                    <th>
                        <i class=""></i>
                        <a href="#">Status</a>
                    </th>
                    <th>
                        <i class=""></i>
                        <a href="#">Free Shipping</a>
                    </th> 
                    <th class="actions">Actions</th>
                </tr>
            </thead>
            <tbody>
                
            </tbody>
        </table>
    </div>
</div>
    