<div class="form-container">    
    <form method="post" action="" class="clearfix">
        <div class="inner-actions" style="width:100%; display: inline-block; text-align: right; margin: 1em 0;">
            <button type="submit" name="save_mode" value="stay" class="form-submit-button btn btn-sm btn-default btn-success" title="Save">Save <span class="glyphicon glyphicon-ok"></span></button>
            <button type="submit" name="save_mode" value="close" class="form-submit-button btn btn-sm btn-default btn-info" title="Save and close">Save and close <span class="glyphicon glyphicon-remove"></span></button>
            <a href="/admin/categories" class="page-close-button btn btn-sm btn-default">Close <span class="glyphicon glyphicon-remove"></span></a>
        </div>

        <div style="display: inline-block; width:100%;">
            <ul class="nav nav-tabs" id="tabbed-menu">
                <li class="active"><a href="#general" data-toggle="tab">General description</a></li>
                <li><a href="#seo" data-toggle="tab">SEO</a></li>
                <li><a href="#banner" data-toggle="tab">Banner</a></li>        
            </ul>
        </div>
        <div class="tab-content">
            <div class="tab-pane active" id="general">
                <div class="form-group">
                    <label for="name" class="control-label">Category name * : </label>
                    <input type="text" id="title" name="category[name]" required="required" title="Name" placeholder="Name" class="form-control" value="<?php echo $category->name; ?>">
                </div>
                <div class="form-group">
                    <label for="description" class="control-label">Description :</label>
                    <textarea name="category[description]" id="detailed_description_field" rows="10" class="form-control wysiwyg"><?php echo $category->description; ?></textarea>
                </div>
                <div class="form-group">
                    <label for="parent_create" class="control-label">Parent category * :</label>
                    <select id="parent_create" required="required" name="category[parent]" class="form-control">
                        <option value="0">Top level</option>
			<?php foreach ($categories as $aCategory) : ?>
			    <?php
			    if ($category->getId() === $aCategory->getId()) {
				continue;
			    }
			    $selected = (isset($parentCategory) && $aCategory->getId() == $parentCategory->getId() ? 'selected' : '');
			    ?>
    			<option value="<?php echo $aCategory->getId(); ?>" <?php echo $selected; ?>><?php echo $aCategory->name; ?></option>
			<?php endforeach; ?>
                    </select>
                </div>
                <div class="form-group ">
                    <label for="visible_create" class="control-label">Visibility</label>
                    <div class="checkbox">
                        <label>
			    <?php $checked = $category->status ? 'checked="checked"' : ''; ?>
                            <input type="checkbox" id="visible_create" name="category[visible]" value="1" <?php echo $checked; ?>>
                            This category is online.
                        </label>
                    </div>
                </div>
            </div>
            <div class="tab-pane" id="seo">
                <div class="group-form">
                    <label for="meta_description" class="control-label">Meta Description :</label>
                    <textarea name="category[meta_description]" id="meta_description" rows="6" placeholder="Make sure it uses keywords found within the page itself." class="form-control"><?php echo $category->meta_description; ?></textarea>
                </div>
                <div class="group-form">
                    <label for="meta_keywords" class="control-label">Meta Keywords :</label>
                    <textarea name="category[meta_keywords]" id="meta_keywords" rows="3" placeholder="Don't repeat keywords over and over in a row. Rather, put in keyword phrases." class="form-control"><?php echo $category->meta_keyword; ?></textarea>
                </div>
            </div>            
            <div class="tab-pane" id="banner">
                <div class="form-group">
                    <label for="banner" class="control-label">Banner :</label>
                    <input type="text" id="banner" name="category[image]" value="<?php echo (isset($category->image) ? $category->image : ''); ?>" class="form-control" placeholder="path/to/image.jpg"/>
                </div>
            </div>
        </div>

        <div class="inner-actions" style="width:100%; display: inline-block; text-align: right; margin: 1em 0;">
            <button type="submit" name="save_mode" value="stay" class="form-submit-button btn btn-sm btn-default btn-success" title="Save">Save <span class="glyphicon glyphicon-ok"></span></button>
            <button type="submit" name="save_mode" value="close" class="form-submit-button btn btn-sm btn-default btn-info" title="Save and close">Save and close <span class="glyphicon glyphicon-remove"></span></button>
            <a href="/admin/categories" class="page-close-button btn btn-sm btn-default">Close <span class="glyphicon glyphicon-remove"></span></a>
        </div>        
    </form>
</div>
<script>

</script>