<div class="wrapper">
    <div class="table-responsive">
        <table class="table table-striped table-condensed" id="category_list">
            <caption>Top level categories
                <a class="btn btn-default btn-primary action-btn" title="Add a new category" href="/admin/categories/add" data-toggle="modal">
                    <span class="glyphicon glyphicon-plus-sign"></span>
                </a>
            </caption>
            <thead>
                <tr>
                    <th class="object-title">
                        <a href="/admin/categories?id_category=0&amp;category_order=id">ID</a>
                    </th>
                    <th class="object-title">
                        <a href="/admin/categories?id_category=0&amp;category_order=alpha">Category title</a>
                    </th>
                    <th>
                        <i class=""></i>
                        <a href="/admin/categories?id_category=0&amp;category_order=visible_reverse">Online</a>
                    </th>                    
                    <th class="actions">Actions</th>
                </tr>
            </thead>
            <tbody>
                <?php if (null === $categories) : ?>                
                    <tr><td colspan="5">No category is found</td></tr>                    
                <?php else: foreach ($categories as $category) : ?>                    
                        <tr>
                            <td><?php echo $category->getId(); ?></td>
                            <td><a href="/admin/categories/open/<?php echo $category->getId(); ?>"><?php echo $category->name; ?></a></td>
                            <td>
                                <?php if ($category->status) : ?>
                                    <i class="glyphicon glyphicon-ok"></i>
                                <?php else : ?>
                                    <i class="glyphicon glyphicon-remove"></i>
                                <?php endif; ?>
                            </td>                    
                            <td class="actions">
                                <div class="btn-group">
                                    <a class="btn btn-default" title="Browse this category" href="/admin/categories/open/<?php echo $category->getId(); ?>"><i class="glyphicon glyphicon-folder-open"></i></a>
                                    <a class="btn btn-default" title="Edit this category" href="/admin/categories/edit/<?php echo $category->getId(); ?>"><i class="glyphicon glyphicon-edit"></i></a>
                                    <a class="btn btn-default category-delete" title="Delete this category and all its contents" href="/admin/categories/delete/<?php echo $category->getId(); ?>"><i class="glyphicon glyphicon-trash"></i></a>
                                </div>
                            </td>
                        </tr>                
                    <?php endforeach;
                endif;
                ?>
            </tbody>
        </table>
    </div>
</div>