<?php if ($this->title): ?>
    <div class="page-title">
        <h1><?php echo $this->title; ?></h1>
    </div>
<?php endif; ?>

<form action="/customer/address/edit_shipping_address_post" method="post" id="form-validate">
    <input type="hidden" name="csrf_token" value="<?php echo \Security::token(); ?>">

    <h2 class="legend">Shipping Information</h2>

    <div class="form-list">
        <p>
            <label for="firstname" class="required"><em>*</em>Firstname</label><br/>
            <input type="text" name="firstname" id="firstname" title="Firstname"
                   value="<?php echo $this->shipping_address->firstname; ?>" class="form-control required-entry">
        </p>

        <p class="field-lastname">
            <label for="lastname" class="required"><em>*</em>Lastname</label><br/>
            <input type="text" name="lastname" id="lastname" title="Lastname"
                   value="<?php echo $this->shipping_address->lastname; ?>" class="form-control required-entry">
        </p>

        <p class="field-telephone">
            <label for="telephone" class="required"><em>*</em>Telephone</label><br/>
            <input type="tel" name="phone" value="<?php echo $this->shipping_address->phone; ?>" id="telephone"
                   title="Telephone" class="form-control required-entry">
        </p>

        <p class="field-mobile">
            <label for="mobile">Mobile</label><br/>
            <input type="tel" name="mobile" value="<?php echo $this->shipping_address->mobile; ?>" id="mobile"
                   title="Mobile" class="form-control">
        </p>

        <p class="field-fax">
            <label for="fax">Fax</label><br/>
            <input type="text" name="fax" value="<?php echo $this->shipping_address->fax; ?>" id="fax" title="Fax"
                   class="form-control">
        </p>
    </div>

    <h2 class="legend">Shipping Address</h2>

    <div class="form-list">
        <p>
            <label for="address_1" class="required"><em>*</em>Address 1</label><br/>
            <input type="text" name="address_1" value="<?php echo $this->shipping_address->address_1; ?>" id="address_1"
                   title="Address 1" class="form-control">
        </p>

        <p>
            <label for="address_2">Address 2</label><br/>
            <input type="text" name="address_2" value="<?php echo $this->shipping_address->address_2; ?>" id="address_2"
                   title="Address 2" class="form-control">
        </p>

        <p>
            <label for="zipcode">Zipcode</label><br/>
            <input type="text" name="zipcode" value="<?php echo $this->shipping_address->zipcode; ?>" id="zipcode"
                   title="Zipcode" class="form-control">
        </p>

        <p>
            <label for="city">City</label><br/>
            <input type="text" name="city" value="<?php echo $this->shipping_address->city; ?>" id="city" title="City"
                   class="form-control">
        </p>

        <p>
            <label for="country_id">Country</label><br/>
            <select name="country_id" onchange="populateZonesByCountry(this.value);
					return false;" class="form-control">
                <option value="">Select the country</option>
                <?php foreach ($this->countries as $country) : ?>
                    <?php $selected = $country['id'] == $this->shipping_address->country_id ? 'selected="selected"' : null; ?>
                    <option
                        value="<?php echo $country['id'] ?>" <?php echo $selected ?>><?php echo $country['name'] ?></option>
                    <?php endforeach; ?>
            </select>
        </p>
        <p>
            <label for="zone_id">Zone/Province</label><br/>
            <select name="zone_id" title="Region|Province|Zone" class="form-control">
                <option value="">Select a zone</option>
                <?php if (isset($this->zones)): ?>
                    <?php foreach ($this->zones as $zone) : ?>
                        <option
                            value="<?php echo $zone['id'] ?>" <?php echo($this->zone_id == $zone['id'] ? 'selected="selected"' : '') ?>><?php echo $zone['name'] ?></option>
                        <?php endforeach; ?>
                    <?php endif; ?>
            </select>
        </p>
    </div>

    <div class="buttons-set">
        <p class="required">* Required Fields</p>
        <button type="submit" title="Save Address" class="btn btn-success">Save Shipping Address</button>
    </div>
</form>