<?php
namespace checkpayment;

use library\Plugin;

class CheckpaymentPlugin extends Plugin
{
    private $html = '';
    private $postErrors = [];

    public $checkName;
    public $address;    

    /**
     * Constructor
     */
    public function __construct($id = null)
    {
        $this->name = '';
        $this->type = '';
        $this->version = '';
        $this->author = '';
        $this->controllers = array('CheckpaymentController', 'CheckpaymentValidation');
        $this->currencies = true;
        $this->currencies_mode = 'checkbox';
        $this->checkName = '';
        $this->address = '';
        $this->bootstrap = true;
        parent::__construct($id);
    }

    /**
     * 
     * @return string
     */
    public function getContent()
    {
        return '<h2>HERE THE CONTENT GENERATED BY MODULE [CHECK-PAYMENT]</h2>';
    }

}
