<!DOCTYPE html>
<html lang="en_US">
<head>
    <meta charset="utf-8"/>
    <title>404 Page Not Found</title>
    <style type="text/css">

        body {
            background-color: #fff;
            margin: 40px;
            font-family: Lucida Grande, Verdana, Sans-serif;
            font-size: 12px;
            color: #000;
        }

        #content {
            border: #999 1px solid;
            background-color: #fff;
            padding: 20px 20px 12px 20px;
            margin: 0 auto;
            width: 800px;
        }

        h1 {
            font-weight: normal;
            font-size: 14px;
            color: #990000;
            margin: 0 0 4px 0;
        }
    </style>
</head>
<body>
<div id="content">
    <h1>404: Page Not Found</h1>
    <?php print_r($data) ?>
    <p>Ooops!, The page you were requesting was not found on this system.</p>
    <hr/>
    <a href="/">Index</a>
</div>
</body>
</html>