<div id="header-bar">
    <ul id="nav">
        <li class="level0 level-top">
            <a href="/" class="home">Home</a>
        </li>
        <li class="level0 level-top">
            <a class="level-top" href="/cart">Shopping Cart</a>
        </li>
        <li class="level0 level-top">
            <a class="level-top" href="/page/contact" title="">Contact us</a>
        </li>
    </ul>
</div>