<div class="wrapper">
    <div class="table-responsive">
        <table class="table table-striped table-condensed" id="currency_list">
            <caption>
                <span class="pull-right">
                    <a class="btn btn-success" title="Add a new currency" href="#add_dialog" data-toggle="modal">
                        <i class="glyphicon glyphicon-plus-sign"></i> Add currency
                    </a>
                </span>
            </caption>
            <thead>
                <tr>                    
                    <th class="object-code">Module</th>
                    <th>Type</th>                    
                    <th>Version</th>                    
                    <th class="actions">Actions</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($this->allActivePlugins as $plugin) :?>
                <tr>
                    <td><?php echo $plugin->getAttribute('displayName'); ?></td>
                    <td><?php echo $plugin->getType(); ?></td>
                    <td><?php echo $plugin->getVersion(); ?></td>
                    <td></td>
                </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>
