<ul id="js-sort-image" class="row list-unstyled ui-sortable">
    <?php foreach ($product->getProductImages() as $image): ?>                    
        <li class="col-sm-6 col-md-3 ui-state-default" data-sort-id="<?php echo $image->getId(); ?>">
    	<a href="" class="thumbnail">
    	    <img src="<?php echo $image->getThumb(); ?>" alt="" width="150" />
    	</a>
    	<div class="btn-group">
    	    <a class="image-update-btn btn btn-default btn-xs disabled js-sorted-position" href="#"><?php echo $image->getId(); ?></a>
    	    <a class="image-update-btn btn btn-default btn-xs" href="/admin/products/update_image/<?php echo $product->getId(); ?>/<?php echo $image->getId(); ?>" data-error-message="Please retry">
    		<span class="glyphicon glyphicon-edit"></span>
    	    </a>		
    	    <a class="image-delete-btn btn btn-default btn-xs" id="image-9" href="/admin/products/delete_image/<?php echo $product->getId(); ?>/<?php echo $image->getId(); ?>" data-error-message="Please retry">
    		<span class="glyphicon glyphicon-trash"></span>
    	    </a>
    	</div>
        </li>                    
    <?php endforeach; ?>
</ul>