<?php if (isset($attribute) && $attribute->getId()) :?>

    <h2>Edit attribute: <?= $attribute->value; ?></h2>
    
    <form action="" method="post">
        <div class="form-group">
            <label for="">Attribute group</label>
            <select class="form-control" disabled="">
                <option value="<?php echo $attributeGroup->getId(); ?>" selected="">
                    <?php echo $attributeGroup->name; ?>
                </option>                
            </select>
            <input type="hidden" name="attributeGroupId" value="<?php echo $attributeGroup->getId();?>">
        </div>
        <div class="form-group">
            <label for="name">Value</label>
            <input class="form-control" type="text" name="value" value="<?php echo $attribute->value; ?>" placeholder="Value attribute">
        </div>
        <div class="form-group">
            <label for="name">Value label</label>
            <input class="form-control" type="text" name="value_label" value="<?php echo $attribute->value_label; ?>" placeholder="Value attribute to display">
        </div>
        <div class="form-group">
            <button class="btn btn-success" type="submit">Edit</button>
        </div>
    </form>

<?php else : ?>
    
    <h2>Add attribute</h2>
    
    <form action="" method="post">
        <div class="form-group">
            <label for="">Attribute group</label>
            <select class="form-control" disabled="">
                <option value="<?php echo $attributeGroup->getId(); ?>" selected="">
                    <?php echo $attributeGroup->name; ?>
                </option>                
            </select>
            <input type="hidden" name="attributeGroupId" value="<?php echo $attributeGroup->getId();?>">
        </div>
        <div class="form-group">
            <label for="name">Value</label>
            <input class="form-control" type="text" name="value" value="" placeholder="Value attribute">
        </div>
        <div class="form-group">
            <label for="name">Value label</label>
            <input class="form-control" type="text" name="value_label" value="" placeholder="Value attribute to display">
        </div>
        <div class="form-group">
            <button class="btn btn-success" type="submit">Add</button>
        </div>
    </form>

<?php endif; ?>
