<div class="wrapper">
    <div class="table-responsive">
        <table class="table table-striped table-condensed fa-border">
            <caption>
                <?php echo __('Attributegroup'); ?>
                <a class="btn btn-default btn-primary action-btn" title="Add a new attributegroup" href="#attributegroup_create_dialog" data-toggle="modal">
                    <span class="glyphicon glyphicon-plus-sign"></span>
                </a>
            </caption>
            <thead>
                <tr>
                    <th>Attribute group</th>
                    <th>Nr. Values</th>
                    <th>Required</th>
                    <th class="actions"></th>
                </tr>
            </thead>
            <?php foreach ($attributeGroups as $attributeGroup) : ?>
                <tr class="js-admin-<?php echo $attributeGroup->id;?>">
                    <td data-field-class="js-name"><?php echo $attributeGroup->name; ?></td>
                    <td data-field-class="js-attribute_count"><?php echo count($attributeGroup->getAttributes()); ?></td>
                    <td data-field-class="js-required"><?php echo $attributeGroup->required;?></td>
                    <td class="actions">
                        <div class="btn-group">
                            <a href="/admin/configuration/attributegroup/view/<?php echo $attributeGroup->getId(); ?>" class="js-view-attributegroup btn btn-default">
                                <i class="glyphicon glyphicon-folder-open"></i>
                            </a>
                            <a class="js-update-attributegroup btn btn-default" href="#attributegroup_update_dialog" data-id="<?php echo $attributeGroup->id;?>" data-toggle="modal">
                                <i class="glyphicon glyphicon-edit"></i>
                            </a>
                            <a title="Delete" class="js-delete-attributegroup btn btn-default" href="#attributegroup_delete_dialog" data-id="<?php echo $attributeGroup->id;?>" data-toggle="modal">
                                <i class="glyphicon glyphicon-trash"></i>
                            </a>
                        </div>
                    </td>
                </tr>
            <?php endforeach; ?>
        </table>
    </div>
</div>

<div class="modal fade " id="attributegroup_update_dialog" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h3>Update attributegroup</h3>
            </div>
            <form method="POST" action="/admin/configuration/attributegroup/edit">
                <input type="hidden" name="_token" value="<?php echo $token?>">
                <input type="hidden" name="id" value="" id="attributegroup_update_id">
                <div class="modal-body">
                    <div class="form-group">
                        <label for="name" class="control-label">Name</label>
                        <input class="form-control js-name" type="text" name="name" value="">
                    </div>
                    <div class="form-group">
                        <label><input class="js-required" type="checkbox" name="required" value="1"> Required</label>                        
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal" aria-hidden="true"><span class="glyphicon glyphicon-remove"></span> Cancel</button>
                    <button  type="submit" class="btn btn-primary"><span class="glyphicon glyphicon-check"></span> Update</button>
                </div>
            </form>
        </div>
    </div>
</div>

<div class="modal fade " id="attributegroup_create_dialog" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h3>Create attributegroup</h3>
            </div>
            <form method="POST" action="/admin/configuration/attributegroup/add">
                <input type="hidden" name="_token" value="<?php echo $token?>">
                <div class="modal-body">
                    <div class="form-group">
                        <label for="name" class="control-label">Name</label>
                        <input class="form-control js-name" type="text" name="name" value="">
                    </div>
                    <div class="form-group">
                        <label><input class="js-required" type="checkbox" name="required"> Required</label>                        
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal" aria-hidden="true"><span class="glyphicon glyphicon-remove"></span> Cancel</button>
                    <button  type="submit" class="btn btn-primary"><span class="glyphicon glyphicon-check"></span> Create</button>
                </div>
            </form>
        </div>
    </div>
</div>

<div class="modal fade" id="attributegroup_delete_dialog" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h3>Delete</h3>
            </div>
            <form method="POST" action="/admin/configuration/attributegroup/delete" id="user_delete_dialog_form">
	            <div class="modal-body">
	                Do you really want to delete this attributegroup ?
                        <input type="hidden" name="id" id="attributegroup_delete_id" value="">
                        <input type="hidden" name="_token" id="attributegroup_delete_id" value="<?php echo $token;?>">
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal" aria-hidden="true"><span class="glyphicon glyphicon-remove"></span> No</button>
                    <button type="submit" class="btn btn-primary"><span class="glyphicon glyphicon-check"></span> Yes</button>
                </div>
            </form>
        </div>
    </div>
</div>

<script type="text/javascript">
jQuery(function($) {
    $(".js-delete-attributegroup").click(function(e){
        $('#attributegroup_delete_id').val($(this).data('id'));
    });
    
    $(".js-update-attributegroup").click(function(e){
        $('#attributegroup_update_id').val($(this).data('id'));
        
        $('.js-admin-' + $(this).data('id')).find('td').each(function(k, v) {
            $v = $(v);

            if(!$v.data('field-class')) {
                return true;
            }
            if ($v.data('value')) {
                var fieldValue = $v.data('value');
            } else {
                var fieldValue = $v.text();
            }            

            $('.' + $v.data('field-class')).val($.trim(fieldValue));

            if( $('.' + $v.data('field-class')).is('input:checkbox')) {
                if (fieldValue == 1) {
                    $('.' + $v.data('field-class')).attr('checked', true);
                } else {
                    $('.' + $v.data('field-class')).attr('checked', false);
                }               
            }
        });
    });
})
</script>

