<div class="wrapper">
    <h2>Attributes > <?= $attributeGroup->name; ?></h2>
    <a class="btn btn-default btn-primary action-btn" title="Add a new attribute"
       href="/admin/attributegroup/add_attribute?attribute_group=<?php echo $attributeGroup->getId(); ?>"
       data-toggle="modal">
        <span class="glyphicon glyphicon-plus-sign"></span>
    </a>

    <div class="container attribute-group">
        <table class="table table-striped table-condensed fa-border">
            <tr>
                <th>ID</th>
                <th>Value</th>
                <th class="actions"></th>
            </tr>
            <?php foreach ($attributes as $attribute) : ?>
                <tr>
                    <td><?php echo $attribute->getId(); ?></td>
                    <td><?php echo $attribute->value; ?></td>
                    <td>
                        <div class="btn-group-action">
                            <div class="btn-group pull-right">
                                <a class="btn btn-default"
                                   href="/admin/attributegroup/edit_attribute/<?php echo $attribute->getId(); ?>"><i
                                        class="glyphicon glyphicon-edit"></i></a>
                                <a class="btn btn-default"
                                   href="/admin/attributegroup/delete_attribute/<?php echo $attribute->getId(); ?>"><i
                                        class="glyphicon glyphicon-trash"></i></a>
                            </div>
                        </div>
                    </td>
                </tr>
            <?php endforeach; ?>
        </table>
    </div>
</div>