<div class="category-home-wrap">
    <div style="margin-bottom: 2rem;">
        <img alt="" src="/html/images/kasoko/banner1.png"/>
    </div>    
    <div class="title-bar">
        <h1><?php echo __('Newest articles');?> <a href="/product/view_all?type=new" class="btn-all">+ <?php echo __('View all'); ?></a></h1>        
    </div>
    <div id="latest">
        <div class="product-container owl-carousel">
            <?php foreach (Product::getLatest(8) as $product) : ?>
            <div class="product-wrap">
                <?php if (count($product->getProductImages())): ?>
                <div class="img-box">
                    <a href="/product/item/<?php echo String::slugify($product->slug); ?>">
                        <?php if ($product->getCoverProductImage() instanceof \library\Product\Image) :?>    
                            <img src="<?php echo $product->getCoverProductImage()->getThumb(); ?>" title="<?php echo $product->name; ?>" alt="<?php echo $product->name; ?>"/>
                        <?php elseif ($product->getFirstProductImage() instanceof \library\Product\Image) : ?>    
                            <img src="<?php echo $product->getFirstProductImage()->getThumb(); ?>" title="<?php echo $product->name; ?>" alt="<?php echo $product->name; ?>"/>
                        <?php else :?>
                            <img itemprop="image" src="/html/images/kasoko/280x196.png" alt="<?php echo $product->name; ?>">
                        <?php endif; ?>
                    </a>
                </div>
                <?php endif; ?>
                <div class="product-meta">
                    <div class="name">
                        <a href="/product/item/<?php echo String::slugify($product->slug); ?>"><?php echo $product->name ?></a>
                    </div>
                    <div class="product-description">
                        <div class="description" itemprop="description"><?php echo \String::truncate($product->description, 100); ?></div>
                    </div>
                    <div class="price"><?php echo String::currency_format($product->price); ?></div>
                    <div class="cart">
                        <a href="javascript:void(0)" class="btn btn-default" onclick="addToCart('<?php echo $product->product_id; ?>');"><?php echo __('Add to Cart');?></a>
                    </div>
                </div>
            </div>        
            <?php endforeach; ?>        
        </div>
    </div>
</div>

<!-- Featured -->
<?php if (!empty($this->featured_products)) :?>
<div id="featured">
    <h1><?php echo __('Featured products');?></h1>
    <div class="featured owl-carousel">
        <?php foreach ($this->featured_products as $product) :?>
        <div class="product-wrap">
            <div class="item">
                <div class="img-box">
                    <a href="/product/item/<?php echo String::slugify($product->slug); ?>">
                        <?php if ($product->getCoverProductImage() instanceof \library\Product\Image) : ?>    
                            <img src="<?php echo $product->getCoverProductImage()->getThumb(); ?>" title="<?php echo $product->name; ?>" alt="<?php echo $product->name; ?>"/>
                        <?php elseif ($product->getFirstProductImage() instanceof \library\Product\Image) : ?>    
                            <img src="<?php echo $product->getFirstProductImage()->getThumb(); ?>" title="<?php echo $product->name; ?>" alt="<?php echo $product->name; ?>"/>
                        <?php else : ?>
                            <img itemprop="image" src="/html/images/kasoko/280x196.png" alt="<?php echo $product->name; ?>" width="150">
                        <?php endif; ?>
                    </a>
                </div>
                <div class="product-meta">
                    <div class="name">
                        <a href="/product/item/<?php echo String::slugify($product->slug); ?>"><?php echo $product->name ?></a>
                    </div>
                    <div class="product-description">
                        <div class="description" itemprop="description"><?php echo \String::truncate($product->description, 100); ?></div>
                    </div>
                    <div class="price"><?php echo String::currency_format($product->price); ?></div>
                    <div class="cart">
                        <a href="javascript:void(0)" class="btn btn-default" onclick="addToCart('<?php echo $product->product_id; ?>');"><?php echo __('Add to Cart');?></a>
                    </div>
                </div>
            </div>
        </div>
        <?php endforeach;?>
    </div>
</div>
<?php endif; ?>
