<h1>My order history</h1>

<?php if (!empty($orders)) : ?>
    <div class="wishlist-info">
        <table>
            <tr>
                <th>Order number</th>
                <th>Date</th>
                <th>Items</th>
                <th>Shipped</th>
                <th>Total</th>
            </tr>
            <?php foreach ($orders as $customerOrder) : ?>
                <tr>
                    <td><a href="/customer/account/order/<?php echo $customerOrder->getId(); ?>">
                            <?php echo $customerOrder->getId(); ?>
                        </a>
                    </td>
                    <td><?php echo date('d-m-Y', strtotime($customerOrder->added_date)); ?></td>
                    <td><?php echo($customerOrder->getItems() ? count($customerOrder->getItems()) : null); ?></td>
                    <td><?php echo $customerOrder->shipped; ?></td>
                    <td><?php echo \Helpers\Stringify::currency_format($customerOrder->amount); ?></td>
                </tr>
            <?php endforeach; ?>
        </table>
    </div>
<?php else : ?>

<?php endif; ?>

