<div class="wrapper">
    <div class="table-responsive">
        <table class="table table-striped table-condensed" id="page_list">
            <caption>Top level cms
                <a class="btn btn-default btn-primary action-btn" title="Add a new page" href="/admin/cms/create_page" data-toggle="modal">
                    <span class="glyphicon glyphicon-plus-sign"></span>
                </a>
            </caption>
            <thead>
                <tr>
                    <th class="object-title">
                        <a href="/admin/cms?id_page=0&amp;page_order=alpha">ID</a>
                    </th>
                    <th class="object-title">
                        <a href="/admin/cms?id_page=0&amp;page_order=alpha">Title</a>
                    </th>
                    <th>
                        <i class=""></i>
                        <a href="/admin/cms?id_page=0&amp;page_order=visible_reverse">Hidden</a>
                    </th>                    
                    <th class="actions">Actions</th>
                </tr>
            </thead>
            <tbody>
                <?php if (null === $pages) : ?>                
                    <tr><td colspan="5">No page is found</td></tr>                    
                <?php else: foreach ($pages as $page) : ?>                    
                        <tr>
                            <td><?php echo $page->getId(); ?></td>
                            <td><a href="/admin/cms/edit/<?php echo $page->getId(); ?>"><?php echo $page->title; ?></a></td>
                            <td>
                                <?php if (!empty($page->hidden)) : ?>
                                    <i class="glyphicon glyphicon-ok"></i>
                                <?php else : ?>
                                    <i class="glyphicon glyphicon-remove"></i>
                                <?php endif; ?>
                            </td>                    
                            <td class="actions">
                                <div class="btn-group">
                                    <a class="btn btn-default btn-xs" title="Edit this page" href="/admin/cms/edit_page/<?php echo $page->getId(); ?>"><i class="glyphicon glyphicon-edit"></i></a>
                                    <a class="btn btn-default btn-xs page-delete" title="Delete this page and all its contents" href="/admin/cms/delete_page/<?php echo $page->getId(); ?>"><i class="glyphicon glyphicon-trash"></i></a>
                                </div>
                            </td>
                        </tr>                
                        <?php
                    endforeach;
                endif;
                ?>
            </tbody>
        </table>
    </div>
</div>