<div class="form-container">    
    <form method="post" action="" class="clearfix">
        <div class="inner-actions" style="width:100%; display: inline-block; text-align: right; margin: 1em 0;">
            <button type="submit" name="save_mode" value="stay" class="form-submit-button btn btn-sm btn-default btn-success" title="Save">Save <span class="glyphicon glyphicon-ok"></span></button>
            <button type="submit" name="save_mode" value="close" class="form-submit-button btn btn-sm btn-default btn-info" title="Save and close">Save and close <span class="glyphicon glyphicon-remove"></span></button>
            <a href="/admin/manufacturers" class="page-close-button btn btn-sm btn-default">Close <span class="glyphicon glyphicon-remove"></span></a>
        </div>
        <div style="display: inline-block; width:100%;">
            <ul class="nav nav-tabs" id="tabbed-menu" style="">
                <li class="active"><a href="#general" data-toggle="tab">General</a></li>                               
            </ul>
            <div class="tab-content">
                <div class="tab-pane active" id="general">
                    <div class="form-group">
                        <label for="name" class="control-label">Manufacturer * :</label>
                        <input type="text" id="name" name="manufacturer[name]" required="required" title="Manufacturer" placeholder="Manufacturer" class="form-control" value="<?php echo $manufacturer->name;?>">
                    </div>
                    <div class="form-group">
                        <label for="" class="control-label">Active :</label>
                        <div class="checkbox">
                            <?php $checked = ($manufacturer->isActive() ? 'checked="checked"' : '');?>
                            <input type="checkbox" id="active" name="manufacturer[active]" value="1" <?php echo $checked;?>/> <label for="active">Active</label>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>
