<div class="wrapper">
    <div class="table-responsive">
        <table class="table table-striped table-condensed" id="product_list">
            <caption>Top level manufacturers
                <a class="btn btn-default btn-primary action-btn" title="Add a new product" href="/admin/manufacturers/add" data-toggle="modal">
                    <span class="glyphicon glyphicon-plus-sign"></span>
                </a>
            </caption>
            <thead>
                <tr>
                    <th class="object-title">
                        <a href="/admin/manufacturers?id_product=0&amp;product_order=id">ID</a>
                    </th>
                    <th class="object-title">
                        <a href="/admin/manufacturers?id_product=0&amp;product_order=alpha">Product title</a>
                    </th>
                    <th>
                        <i class=""></i>
                        <a href="/admin/manufacturers?id_product=0&amp;product_order=visible_reverse">Online</a>
                    </th>                    
                    <th class="actions">Actions</th>
                </tr>
            </thead>
            <tbody>
            <?php if (null === $allManufacturers) :?>                
                <tr><td colspan="5">No manufacturer is found</td></tr>                    
            <?php else: foreach($allManufacturers as $manufacturer) :?>
                <tr>
                    <td><?php echo $manufacturer->getId();?></td>
                    <td><a href="/admin/manufacturers/edit/<?php echo $manufacturer->getId();?>"><?php echo $manufacturer->name;?></a></td>
                    <td>
                        <?php if ($manufacturer->isActive()) :?>
                            <i class="glyphicon glyphicon-ok"></i>
                        <?php else :?>
                            <i class="glyphicon glyphicon-remove"></i>
                        <?php endif;?>
                    </td>                    
                    <td class="actions">
                        <div class="btn-group">
                            <a class="btn btn-default btn-xs" title="Edit this product" href="/admin/manufacturers/edit/<?php echo $manufacturer->getId();?>"><i class="glyphicon glyphicon-edit"></i></a>
                            <a class="btn btn-default btn-xs product-delete" title="Delete this product and all its contents" href="/admin/manufacturers/delete/<?php echo $manufacturer->getId();?>"><i class="glyphicon glyphicon-trash"></i></a>
                        </div>
                     </td>
                </tr>                
            <?php endforeach; endif; ?>
            </tbody>
        </table>
    </div>
</div>