<div class="checkout-heading">
    <?php echo $progressHtml; ?>
</div>

<div class="checkout">
    <div id="checkout">        
        <h1><?php echo $this->title; ?></h1>
        <div id="step1" class="checkout-content">
            <div class="left">
                <h2>New Customer</h2>                
                <p>By creating an account you will be able to shop faster, be up to date on an order's status, and keep track of the orders you have previously made.</p>
                <button class="btn btn-primary" type="button" id="button-account">Register account</button>
            </div>
	    <!-- Login -->
            <div class="right" id="login">
                <h2>Returning Customer</h2>
                <p>I am a returning customer</p>
                <p>
                    <label for="">E-mail</label><br />
                    <input type="email" name="email" value="" placeholder="e-mail" class="form-control" />
                </p>
                <p>
                    <label for="">Password</label><br>
                    <input type="password" value="" name="password" placeholder="password" class="form-control" />
                </p>
                <p>
                    <a href="/account/forgotten">Forgotten Password</a>
                </p>
                <p>
                    <button class="btn btn-success" type="button" id="button-login">Login</button>
                </p>
            </div>
        </div>        
    </div>
</div>