<div id="step1"> 
    <div class="right" id="login">
        <h2>Returning Customer</h2>
        <p>I am a returning customer</p>
        <p>
            <label for=""><b>E-mail:</b></label><br />
            <input type="email" name="email" value="" placeholder="" class="form-control">
        </p>    
        <p>
            <label for=""><b>Password:</b></label><br>
            <input type="password" name="password" value="" class="form-control">
        </p>
        <p>
            <a href="/account/forgotten">Forgotten Password</a>
        </p>        
        <p>
            <input type="button" class="" id="button-login" value="Login">
        </p>    
    </div>
</div>