<div class="wrapper">
    <div class="table-responsive">
        <table class="table table-striped table-condensed" id="currency_list">
            <caption>
                <span class="pull-right">
                    <a class="btn btn-success" title="Add a new currency" href="#add_dialog" data-toggle="modal">
                        <i class="glyphicon glyphicon-plus-sign"></i> Add currency
                    </a>
                </span>
            </caption>
            <thead>
                <tr>
                    <th class="object-id">ID</th>
                    <th class="object-code">Code</th>
                    <th>Symbol</th>                    
                    <th>Exchange Rate</th>
                    <th>Default</th>
                    <th class="actions">Actions</th>
                </tr>
            </thead>
            <tbody>
                <?php if (null === $currencies) : ?>                
                    <tr>
                        <td colspan="5">No currency is found</td>
                    </tr>                    
                <?php else: ?>
                    <?php foreach ($currencies as $currency) : ?>                    
                        <tr>
                            <td><?php echo $currency->getId(); ?></td>
                            <td><?php echo $currency->getCode(); ?></td>
                            <td><?php echo $currency->symbol; ?></td>                            
                            <td><?php echo $currency->getRate(); ?></td>
                            <td><?php echo $currency->default; ?></td>
                            <td class="actions">
                                <div class="btn-group">
                                    <a class="currency-change btn btn-default" title="Change this currency" href="/admin/configuration/currency/edit?currency_id=<?php echo $currency->getId(); ?>">
                                        <span class="glyphicon glyphicon-edit"></span>
                                    </a>
                                </div>
                            </td>
                        </tr>                
                    <?php endforeach; ?>
                <?php endif; ?>
            </tbody>
        </table>
    </div>
</div>

<div class="modal fade in" id="creation_dialog" tabindex="-1" aria-hidden="false">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">x</button>
                <h3>Add a new currency</h3>
            </div>
            <form method="POST" action="/admin/configuration/currency/add">
                <div class="modal-body">
                    <div class="form-group">
                        <label for="code" class="control-label">Code</label>
                        <input type="text" id="code" required="required" name="currency_creation[code]" class="form-control" value="" title="Currency code" placeholder="Code">
                    </div>
                    <div class="form-group">
                        <label for="symbol" class="control-label">Symbol</label>
                        <input type="text" id="symbol" required="required" name="currency_creation[symbol]" class="form-control" value="" title="Currency symbol" placeholder="Symbol">
                    </div>
                    <div class="form-group">
                        <label for="" class="control-label">Exchange rate</label>
                        <input type="text" id="name" required="required" name="currency_creation[rate]" class="form-control" value="" title="Currency exchange rate" placeholder="Exchange rate">
                    </div>
                </div>    
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal" aria-hidden="true"><span class="glyphicon glyphicon-remove"></span> Cancel</button>
                    <button type="submit" class="btn btn-primary"><span class="glyphicon glyphicon-check"></span> Create this currency</button>
                </div>
            </form>
        </div>
    </div>
</div>

<script>
	$(document).on('click', '#currency-rate-update-button', function () {
		var updateButton = $('#currency-rate-update-button');
		$.ajax({
			url: '/admin/configuration/currency/update_rates',
			data: {token: ("<?php echo Security::token(); ?>")},
			success: function (data) {
				updateButton.removeClass('btn-info').addClass('btn-success').show(500, function () {
					setTimeout(function () {
						updateButton.removeClass('btn-success').addClass('btn-info');
					}, 2000);
				});
			},
			error: function (xhr, status, error) {
				updateButton.removeClass('btn-info').addClass('btn-danger').show(500, function () {
					setTimeout(function () {
						updateButton.removeClass('btn-danger').addClass('btn-info');
					}, 2000);
				});
			}
		});
		return false;
	});
</script>