<div class="container">
    <h1>
        <?php echo __('configuration'); ?>
    </h1>
    <div class="col-md-4">
        <h2>Product catalog configuration</h2>
        <div>
            <ul>
                <li><a href="/admin/configuration/attributegroup">Product attributes</a></li>
                <li><a href="/admin/configuration/features">Product features</a></li>
                <li><a href="/admin/configuration/currency">Currencies</a></li>
                <li><a href="/admin/configuration/taxes_rules">Taxes and Tax rules</a></li>
            </ul>
        </div>
    </div>
    <div class="col-md-4">
        <h2>Shipping configuration</h2>
    </div>
    <div class="col-md-4">
        <h2>System settings</h2>
        <div>
            <ul>
                <li><a href="/admin/configuration/settings">Settings</a></li>
                <li><a href="/admin/configuration/store">Store</a></li>                
                <li><a href="/admin/configuration/users">Users</a></li>
                <li><a href="/admin/configuration/languages">Languages</a></li>
                <li><a href="/admin/configuration/plugins">Plug-Ins</a></li>
            </ul>
        </div>
    </div>
</div>
